export enum AppIcon {
  home = 'home',
  list = 'list',
  book = 'book',
  settings = 'settings',
  favorite = 'favorite',
  search = 'search',
  notifications = 'notifications',
  ellipsis = 'ellipsis',
  info = 'info',
  close = 'close',
  apps = 'apps',
  menu = 'menu',
  avatar = 'account_circle',
}
